[package]
name = "local_cache"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/local_cache.rs"

[dependencies]
anyhow.workspace = true
cache = { path = "../cache" }
chrono = { version = "0.4", features = ["serde"] }
heed = "0.22"
serde.workspace = true
serde_json.workspace = true
